print("What's your name?")
Name = input()
print("Welcome, {0}.".format(Name))
print("How are you feeling?")
Mood = input()
print("That's good.")
print("Hey, {0}, what's your favorite restaurant?".format(Name))
Restaurant = input()
print("What's your favorite food, {0}?".format(Name))
Food = input()
print("Enter 7 Adjectives.")
Adjective1 = input()
Adjective2 = input()
Adjective3 = input()
Adjective4 = input()
Adjective5 = input()
Adjective6 = input()
Adjective7 = input()
print("Enter 5 Nouns.")
Noun1 = input()
Noun2 = input()
Noun3 = input()
Noun4 = input()
Noun5 = input()
print("Enter 3 verbs that end with -ing.")
Verbing1 = input()
Verbing2 = input()
Verbing3 = input()
print("Enter a noun in the plural tense.")
PluralNoun = input()
print("Enter an animal.")
Animal = input()
print("Enter an adverb.")
Adverb = input()
print("Now finally, enter 2 verbs in the past tense.")
PastVerb = input()
PastVerb1 = input()

print("My name is {0}.".format(Name))
print("I'm a student at {0} {1} Academy.".format(Adjective1, Noun1))
print("My best friend's name is Minerva, who is as {0} as a {1}.".format(Adjective2, Noun2))
print("My other best friend's name is Fuyumi, who is skilled at {0}, and has a passion for {1}.".format(Verbing1, PluralNoun))
print("Today at lunch, Fuyumi, Minerva, and I headed over to our favorite restaurant, {0}, to order some {1}.".format(Restaurant, Food))
print("At {0}, we ran into Minerva and Fuyumi's friends, Julien and Dimitri.".format(Restaurant))
print("Julien is very {0}, and excels at {1}.".format(Adjective3, Verbing2))
print("Dimitri can be a bit of a {0} {1}, but he and I bond over {2}.".format(Adjective4, Noun3, Verbing3))
print("Minerva and Fuyumi invited Julien and Dimitri to join us for lunch but then, a {0} {1} appeared {2}!".format(Adjective5, Animal, Adverb))
print("We were so shocked, that Minerva dropped her {0} and Fuyumi spat her {0} onto Dimitri's shirt.".format(Food))
print("We both {0} but then the {1} {2} would not relent.".format(PastVerb, Adjective6, Animal))
print("Dimitri grabbed out a {0} from his bag and Julien reached for a {1} behind the counter.".format(Noun4, Noun5))
print("Dimitri and Julien successfully scared away the {0} {1}.".format(Adjective7, Animal))
print("Fuyumi and Minerva were so {0} that they {1} the two men as a thank you.".format(Mood, PastVerb1))
